# fly.toml app configuration file generated for curso-django-fly on 2023-04-24T20:37:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "curso-django-fly"
primary_region = "gru"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

#[[statics]]
#  guest_path = "/code/static"
#  url_prefix = "/static/"

[deploy]
  release_command = "python manage.py migrate --noinput"  
